# Generated by Django 4.2.29 on 2026-03-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="modality",
            field=models.CharField(
                choices=[
                    ("presencial", "Presencial"),
                    ("virtual", "Virtual"),
                    ("hibrido", "Hibrido"),
                ],
                default="presencial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="admin_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="worker_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmado"),
                    ("pending", "Pendiente"),
                    ("cancelled", "Cancelado"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("organizer", "Organizador"),
                    ("student", "Estudiante"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
